### ISSUE TITLE
Flag : Statistics generated heavily fluctuated 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#81] opened 2021-11-30 14:10 UTC
Let’s take this changeset as an example,
https://www.openstreetmap.org/changeset/88698067#map=12/11.9245/75.5825
Here as we can see there are lots of building added definitely more than one but in the underpass, I can see only one school and building added, It has heavily fluctuated 
![image](https://user-images.githubusercontent.com/36752999/144062461-ca69fd87-00e0-4865-8724-ca89af6a9350.png)
Here Tag is for most of them , that might be reason 
building | school

**Comment by itskshitiz321** [comment] 2021-12-01 09:24
Here is Another Example to look at: 
**Changeset** : 110330551 
**Stats calculated in underpass** : Null ,
**Total Buildings in that area** : 24 (from insight ) 
**Do they have buildings = yes tag** ? Yes 
**Resources** : 
https://www.openstreetmap.org/changeset/110330551#map=15/27.6254/91.4842
![image](https://user-images.githubusercontent.com/36752999/144207433-e48a002d-fa49-4ed4-b7ea-e8df0bebda29.png)

**Comment by itskshitiz321** [comment] 2021-12-01 09:36
Now I can confirm that  underpass is escaping calculations even they have building=yes tag 
**More Examples:** Changeset 110330730( 14 from insight 0 from underpass) , 110330928( 2 from insight 0 from underpass), 110331666 ( here buildings newly created are 41 but in underpass it is null ), 110331783 ( 14 from insight 0 from underpass)

**Comment by itskshitiz321** [comment] 2021-12-02 09:10
cc : @robsavoye

**Comment by ramyaragupathy** [comment] 2022-01-05 09:57
Related to https://github.com/hotosm/underpass/issues/79

**Comment by emi420** [comment] 2022-05-13 15:34
Fluctuations with stats stored in the DB were caused by issues with replication: some changesets/osmchange files were not downloaded and processed. Those issues are fixed now.

Regarding stats calculation, I extracted stats from all cited changesets using Underpass `stats-test` and result are good for all of them.

### Changeset 110330551

Running stats-test Underpass returns the correct stats for added building:

```json
{
  "changeset_id": 110330551,
  "filespec": "/code/testsuite/testdata/stats/110330551.xml",
  "added": [
    {
      "building": 24
    }
  ],
  "modified": []
}
```

### Changest 110330730

Running stats-test Underpass returns the correct stats for added building:

```json
{
  "changeset_id": 110330730,
  "filespec": "/code/testsuite/testdata/stats/110330730.xml",
  "added": [
    {
      "building": 14
    }
  ],
  "modified": []
}
```

### Changest 110330928

Running stats-test Underpass returns the correct stats for added building:

```json
{
  "changeset_id": 110330928,
  "filespec": "/code/testsuite/testdata/stats/110330928.xml",
  "added": [
    {
      "building": 2
    }
  ],
  "modified": [
    {
      "highway": 1
    },
    {
      "highway_km": 119057110
    }
  ]
}
```
### Changest 110331666

Running stats-test Underpass returns the correct stats for added building:

```json
{
  "changeset_id": 110331666,
  "filespec": "/code/testsuite/testdata/stats/110331666.xml",
  "added": [
    {
      "building": 41
    }
  ],
  "modified": [
    {
      "highway": 1
    }
  ]
}
```

### Changest 110331783

Running stats-test Underpass returns the correct stats for added building:

```json
{
  "changeset_id": 110331783,
  "filespec": "/code/testsuite/testdata/stats/110331783.xml",
  "added": [
    {
      "building": 14
    }
  ],
  "modified": [
    {
      "building": 1
    },
    {
      "highway": 1
    },
    {
      "highway_km": 28703384
    }
  ]
}
```

**Closed** 2022-05-18 14:14 UTC
Labels: type:bug, priority:high
